# Generated by Django 5.0.1 on 2024-03-02 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piauth', '0002_customuser_address_customuser_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
