# Generated by Django 5.0.3 on 2024-03-10 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piauth', '0007_customuser_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_verified',
        ),
    ]
