# Generated by Django 5.0.3 on 2024-03-10 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piauth', '0008_remove_customuser_email_verified'),
    ]

    operations = [
    ]
