# Generated by Django 5.0.1 on 2024-03-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piapp', '0006_customuser_delete_user_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
