# Generated by Django 5.0.1 on 2024-03-01 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piapp', '0007_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
